# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from docling.proto import inference_pb2 as docling_dot_proto_dot_inference__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in docling/proto/inference_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InferenceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Prompt = channel.unary_unary(
                '/Inference.Inference/Prompt',
                request_serializer=docling_dot_proto_dot_inference__pb2.PromptRequest.SerializeToString,
                response_deserializer=docling_dot_proto_dot_inference__pb2.CompletionResponse.FromString,
                _registered_method=True)
        self.StreamPrompt = channel.unary_stream(
                '/Inference.Inference/StreamPrompt',
                request_serializer=docling_dot_proto_dot_inference__pb2.PromptRequest.SerializeToString,
                response_deserializer=docling_dot_proto_dot_inference__pb2.CompletionResponse.FromString,
                _registered_method=True)
        self.Completion = channel.unary_unary(
                '/Inference.Inference/Completion',
                request_serializer=docling_dot_proto_dot_inference__pb2.CompletionRequest.SerializeToString,
                response_deserializer=docling_dot_proto_dot_inference__pb2.CompletionResponse.FromString,
                _registered_method=True)
        self.StreamCompletion = channel.unary_stream(
                '/Inference.Inference/StreamCompletion',
                request_serializer=docling_dot_proto_dot_inference__pb2.CompletionRequest.SerializeToString,
                response_deserializer=docling_dot_proto_dot_inference__pb2.CompletionResponse.FromString,
                _registered_method=True)


class InferenceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Prompt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamPrompt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Completion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamCompletion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Prompt': grpc.unary_unary_rpc_method_handler(
                    servicer.Prompt,
                    request_deserializer=docling_dot_proto_dot_inference__pb2.PromptRequest.FromString,
                    response_serializer=docling_dot_proto_dot_inference__pb2.CompletionResponse.SerializeToString,
            ),
            'StreamPrompt': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamPrompt,
                    request_deserializer=docling_dot_proto_dot_inference__pb2.PromptRequest.FromString,
                    response_serializer=docling_dot_proto_dot_inference__pb2.CompletionResponse.SerializeToString,
            ),
            'Completion': grpc.unary_unary_rpc_method_handler(
                    servicer.Completion,
                    request_deserializer=docling_dot_proto_dot_inference__pb2.CompletionRequest.FromString,
                    response_serializer=docling_dot_proto_dot_inference__pb2.CompletionResponse.SerializeToString,
            ),
            'StreamCompletion': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamCompletion,
                    request_deserializer=docling_dot_proto_dot_inference__pb2.CompletionRequest.FromString,
                    response_serializer=docling_dot_proto_dot_inference__pb2.CompletionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Inference.Inference', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Inference.Inference', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Inference(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Prompt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Inference.Inference/Prompt',
            docling_dot_proto_dot_inference__pb2.PromptRequest.SerializeToString,
            docling_dot_proto_dot_inference__pb2.CompletionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamPrompt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/Inference.Inference/StreamPrompt',
            docling_dot_proto_dot_inference__pb2.PromptRequest.SerializeToString,
            docling_dot_proto_dot_inference__pb2.CompletionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Completion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Inference.Inference/Completion',
            docling_dot_proto_dot_inference__pb2.CompletionRequest.SerializeToString,
            docling_dot_proto_dot_inference__pb2.CompletionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamCompletion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/Inference.Inference/StreamCompletion',
            docling_dot_proto_dot_inference__pb2.CompletionRequest.SerializeToString,
            docling_dot_proto_dot_inference__pb2.CompletionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
